version: '3'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --wait_timeout=28800 --innodb-file-per-table=1 --skip-innodb-read-only-compressed
# I saw this command in few tutorials and add it here 
    volumes:
      - /mnt/NC/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123root123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123123
   # Use name of service (db) when you write database credention (name,pass & etc.)  Uncheck to install default programs - collabora lagging the system. 
    deploy:
       mode: global
       placement:
        constraints: [node.hostname == docker-master] 
        
  app:
    image: linuxserver/nextcloud:23.0.0
    # i tried defferent image and "original" as well. This one is ssl config ( better for nginx proxy manager)  and is quicly response and so on.
    container_name: nextcloud
    restart: always
    links:
      - db
    depends_on:
      - redis
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123123
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=PassworD
      - NEXTCLOUD_TRUSTED_DOMAINS=yourdomainname.com
      - TRUSTED_PROXIES=172.0.0.0/12
    ports:
      - 8866:443
    volumes:
      - /mnt/NC/nextcloud/config:/config
      - /mnt/NC/nextcloud/data:/data   
    deploy:
       mode: global
       placement:
        constraints: [node.hostname == docker-master] 

  redis:
    image: redis:latest
    command: redis-server --requirepass PassworD
#redis-server --appendonly yes
    restart: always
    volumes:
      - /mnt/NC/redis:/data
     # some config exemples use var/lib/data directory, but for me this doesn't work and find redis store this data in /data folder
    deploy:
       mode: global
       placement:
        constraints: [node.hostname == docker-master] 
        
#You need to make some changes to nrxtcloud config file and add redis as service for https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
# depence of your settup  'host' shuold be diferent. In mine case I use "redis" as host and work perfect  

  
 
