version: '3'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --wait_timeout=28800 --innodb-file-per-table=1 --skip-innodb-read-only-compressed
# I saw this command in few tutorials and add it here :) 
    volumes:
      - /mnt/NC/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=BrewrwerwknLGcnUjHtk
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=HFdMrwer123qc8v86Pre5dsad
   # Use name of service (db) when you write database credention (name,pass & etc.)  Uncheck to install default programs - collabora lagging the system. 
    deploy:
       mode: global
       placement:
        constraints: [node.hostname == docker-master] 
        
  app:
    image: linuxserver/nextcloud:23.0.0
    # i tried defferent image and "original" as well. This one is ssl config ( better for nginx proxy manager)  and is quicly response and so on.
    container_name: nextcloud
    restart: always
    links:
      - db
    depends_on:
      - redis
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sofia
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=HFdMrwer123qc8v86Pre5dsad
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=1.topigri.com
      - TRUSTED_PROXIES=172.0.0.0/12
    ports:
      - 8866:443
    volumes:
      - /mnt/NC/nextcloud/config:/config
      - /mnt/NC/nextcloud/data:/data   
    deploy:
       mode: global
       placement:
        constraints: [node.hostname == docker-master] 

  redis:
    image: redis:latest
    restart: always
    volumes:
      - /mnt/NC/redis:/var/lib/redis
    deploy:
       mode: global
       placement:
        constraints: [node.hostname == docker-master] 


  
 
